const OPENAI_URL = 'https://api.openai.com/v1/responses';
const ALLOWED_EVENTS = new Set(['player_message','invalid_action','system_block','showdown_reaction','hand_reaction','identity_analysis','action_reaction','phase_transition','opponent_performance']);
const PERSONA_RULES = {
  student:'活潑大學生：自然、親切、反應快；少量語助詞、低頻 emoji，不幼稚。',
  executive:'外商公司 CEO：俐落、專業、穩定，有管理者節奏；極少量自然英文。',
  moon:'月之精靈：冷冽、疏離、淡淡上對下；短句、克制、留白。'
};
function send(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));}
function extractText(response){if(typeof response?.output_text==='string'&&response.output_text.trim())return response.output_text.trim();for(const item of response?.output||[])for(const part of item?.content||[])if(part?.type==='output_text'&&typeof part.text==='string'&&part.text.trim())return part.text.trim();return ''}
function cleanText(x,n){return typeof x==='string'?x.slice(0,n):''}
function sanitizeState(body){if(!body||body.schema_version!=='dealer-state-v1'||!ALLOWED_EVENTS.has(body.event_type))return null;const persona=body?.dealer?.persona;if(!PERSONA_RULES[persona])return null;const extra=body.extra||{},identity=body.event_type==='identity_analysis';return {schema_version:'dealer-state-v1',event_type:body.event_type,match:{hand:Number(body?.match?.hand??0),total_hands:5,hero_stack:Number(body?.match?.hero_stack??0),opponent_stack:Number(body?.match?.opponent_stack??0),pot:Number(body?.match?.pot??0),hand_ended:!!body?.match?.hand_ended,match_ended:!!body?.match?.match_ended},table:{street:cleanText(body?.table?.street,16),board:Array.isArray(body?.table?.board)?body.table.board.slice(0,5).map(String):[],hero_hole:Array.isArray(body?.table?.hero_hole)?body.table.hero_hole.slice(0,2).map(String):[],opponent_hole_visible:Array.isArray(body?.table?.opponent_hole_visible)?body.table.opponent_hole_visible.slice(0,2).map(String):null,hero_position:cleanText(body?.table?.hero_position,16),actor:['hero','opp'].includes(body?.table?.actor)?body.table.actor:null,hero_to_call:body?.table?.hero_to_call==null?null:Number(body.table.hero_to_call),current_bet:Number(body?.table?.current_bet??0)},dealer:{persona,conversation:Array.isArray(body?.dealer?.conversation)?body.dealer.conversation.slice(-10).map(t=>({role:t?.role==='hunter'?'hunter':'dealer',text:cleanText(t?.text,220)})).filter(t=>t.text):[]},extra:{message:cleanText(extra.message,240),winner:cleanText(extra.winner,12),amount:Number(extra.amount??0),heroHand:cleanText(extra.heroHand,40),oppHand:cleanText(extra.oppHand,40),matchEnded:!!extra.matchEnded,guess:identity?cleanText(extra.guess,8):'',actual:identity?cleanText(extra.actual,8):'',correct:identity&&!!extra.correct,reason:identity?cleanText(extra.reason,700):'',history:identity?cleanText(extra.history,7000):''}}}
function buildInstructions(persona,eventType){
  const base=`你是 FIVE-HAND HUNTER 的 Dealer 表演層。程式負責真相，AI 只負責表演。\n硬邊界：不得重算或改寫 Pot、Stack、Board、Hole Cards、Action、Winner；不得替 Hunter 決策；只處理這一次事件，不重新回答對話歷史中的舊問題；只輸出繁體中文荷官台詞，不輸出標籤、JSON 或 Markdown。\n目前事件：${eventType}。人格：${PERSONA_RULES[persona]}`;
  if(eventType!=='identity_analysis')return `${base}\n這是牌局進行中的表演。只回應當前公開事件或直接指定給 Dealer 的訊息；不得討論、評價或提示其他遊戲階段、分類、線索與推理。台詞簡短，不重播程式已顯示的完整牌桌狀態。`;
  return `${base}\n這是牌局結束後的正式檢討。actual/correct 是程式真相。Hunter 行動只能描述對手面對的刺激，不能當作 Opponent 身份證據。強證據排序：核心機制（NPC 穩定 Bias / GTO Baseline discipline / GPT Evidence→Adaptation）> sizing/frequency/sequence/cross-hand adjustment > 語言、情緒、沉默等表面風格。若 decision space 或 evidence 不足，明說不確定；Hunter 沒理由就不要替他發明理由。`;
}
function violatesPokerSilence(text){return /(NPC|GTO|GPT|身份|證據|evidence|bias|baseline|bayesian|貝葉斯|線索|暗示|推測)/i.test(text)}
function safePokerLine(eventType){if(eventType==='hand_reaction')return '本手結束，準備下一手。';if(eventType==='showdown_reaction')return '牌面與結果已確認。';if(eventType==='action_reaction')return '行動已確認。';return '收到。牌桌繼續。'}
export default async function handler(req,res){if(req.method!=='POST')return send(res,405,{error:'method_not_allowed'});if(!process.env.OPENAI_API_KEY)return send(res,503,{error:'openai_not_configured'});const state=sanitizeState(req.body);if(!state)return send(res,400,{error:'invalid_dealer_state'});try{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);const upstream=await fetch(OPENAI_URL,{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',instructions:buildInstructions(state.dealer.persona,state.event_type),input:`以下是程式鎖定事件，只根據它生成完整、不截斷的台詞：\n${JSON.stringify(state)}`,max_output_tokens:state.event_type==='identity_analysis'?520:180}),signal:controller.signal});clearTimeout(timeout);const data=await upstream.json().catch(()=>({}));if(!upstream.ok){console.error('OpenAI dealer error',upstream.status,data?.error?.message||data);return send(res,502,{error:'openai_error'});}let text=extractText(data);if(!text)return send(res,502,{error:'empty_model_output'});if(state.event_type!=='identity_analysis'&&violatesPokerSilence(text))text=safePokerLine(state.event_type);return send(res,200,{text});}catch(err){console.error('Dealer endpoint failure',err?.name||err?.message||err);return send(res,504,{error:err?.name==='AbortError'?'openai_timeout':'dealer_endpoint_failure'});}}
